from enum import Enum

class UserRole(str, Enum):
    APPLICANT = "APPLICANT"
    OFFICER = "OFFICER"
    ADMIN = "ADMIN"

class ApplicationType(str, Enum):
    NEW_LICENSE = "NEW_LICENSE"
    RENEWAL = "RENEWAL"
    MODIFICATION = "MODIFICATION"

class ApplicationStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    DOCUMENT_QUERY = "DOCUMENT_QUERY"
    INSPECTION_REQUIRED = "INSPECTION_REQUIRED"
    INSPECTION_SCHEDULED = "INSPECTION_SCHEDULED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"

class OwnershipType(str, Enum):
    OWNED = "OWNED"
    RENTED = "RENTED"
    LEASED = "LEASED"
    CONSENTED = "CONSENTED"
    OTHER = "OTHER"

class BusinessType(str, Enum):
    HOME_BASED = "HOME_BASED"
    OFFICE = "OFFICE"
    MANUFACTURING_UNIT = "MANUFACTURING_UNIT"
    PROCESSING_UNIT = "PROCESSING_UNIT"
    RESTAURANT = "RESTAURANT"
    RETAIL = "RETAIL"
    WAREHOUSE = "WAREHOUSE"
    DISTRIBUTOR = "DISTRIBUTOR"
    OTHER = "OTHER"

class OrganizationType(str, Enum):
    PROPRIETORSHIP = "PROPRIETORSHIP"
    PARTNERSHIP = "PARTNERSHIP"
    LLP = "LLP"
    PRIVATE_LIMITED = "PRIVATE_LIMITED"
    PUBLIC_LIMITED = "PUBLIC_LIMITED"
    SOCIETY = "SOCIETY"
    TRUST = "TRUST"
    COOPERATIVE = "COOPERATIVE"
    OTHER = "OTHER"

class ProjectStage(str, Enum):
    NEW = "NEW"
    EXISTING = "EXISTING"
    EXPANSION = "EXPANSION"
    MODIFICATION = "MODIFICATION"

class ActivityType(str, Enum):
    MANUFACTURING = "MANUFACTURING"
    PROCESSING = "PROCESSING"
    PACKAGING = "PACKAGING"
    RELABELLING = "RELABELLING"
    STORAGE = "STORAGE"
    WHOLESALE = "WHOLESALE"
    RETAIL = "RETAIL"
    RESTAURANT = "RESTAURANT"
    CATERING = "CATERING"
    DISTRIBUTION = "DISTRIBUTION"
    TRANSPORT = "TRANSPORT"
    OTHER = "OTHER"

class ApplicabilityType(str, Enum):
    MANDATORY = "MANDATORY"
    CONDITIONAL = "CONDITIONAL"
    OPTIONAL = "OPTIONAL"
    NOT_APPLICABLE = "NOT_APPLICABLE"

class DocumentReviewStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PENDING_REVIEW = "PENDING_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    NEEDS_CORRECTION = "NEEDS_CORRECTION"

class QueryStatus(str, Enum):
    OPEN = "OPEN"
    RESPONDED = "RESPONDED"
    RESOLVED = "RESOLVED"

class InspectionStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RESCHEDULED = "RESCHEDULED"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
